// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY0ANE9V--fvi8DeJRZ6jPa-x4AdevhBM',
    appId: '1:34653800211:web:a299cd1d3deff390d27ce6',
    messagingSenderId: '34653800211',
    projectId: 'mynotes-proj-divyam2',
    authDomain: 'mynotes-proj-divyam2.firebaseapp.com',
    storageBucket: 'mynotes-proj-divyam2.appspot.com',
    measurementId: 'G-N4SR99D27S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrJGCGyCRui49M2pRPmG5waT06syxC5y4',
    appId: '1:34653800211:android:615fbdba71c58cc4d27ce6',
    messagingSenderId: '34653800211',
    projectId: 'mynotes-proj-divyam2',
    storageBucket: 'mynotes-proj-divyam2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoEgSbmewlZmBrfOEfWCAuRhyq5Uisf2w',
    appId: '1:34653800211:ios:0e5607e634b51bbed27ce6',
    messagingSenderId: '34653800211',
    projectId: 'mynotes-proj-divyam2',
    storageBucket: 'mynotes-proj-divyam2.appspot.com',
    iosBundleId: 'com.blah.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoEgSbmewlZmBrfOEfWCAuRhyq5Uisf2w',
    appId: '1:34653800211:ios:0e5607e634b51bbed27ce6',
    messagingSenderId: '34653800211',
    projectId: 'mynotes-proj-divyam2',
    storageBucket: 'mynotes-proj-divyam2.appspot.com',
    iosBundleId: 'com.blah.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY0ANE9V--fvi8DeJRZ6jPa-x4AdevhBM',
    appId: '1:34653800211:web:802094de882e7951d27ce6',
    messagingSenderId: '34653800211',
    projectId: 'mynotes-proj-divyam2',
    authDomain: 'mynotes-proj-divyam2.firebaseapp.com',
    storageBucket: 'mynotes-proj-divyam2.appspot.com',
    measurementId: 'G-YD3FYD9NR4',
  );
}
